spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-kafka-demo

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: spring-kafka-group
      isolation-level: read_committed
    producer:
      transaction-id-prefix: tx-
    streams:
      application-id: wordcount-streams-app
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        state.dir: ./data/kafka-streams


server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# Consumer groups to start automatically at app boot
# Set enabled: false to skip auto-start for that group
kafka:
  consumer-groups:
    - group-id: group-1
      topic: rebalance-test
      enabled: true
    - group-id: group-2
      topic: rebalance-test
      enabled: true

logging:
  level:
    root: INFO
    com.example.kafka: DEBUG
    org.apache.kafka: WARN